config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'local_emails#index'
  resources :local_emails, except:[:index] do
    member do
      post :send_mail
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/local_email.rb
class LocalEmail < ApplicationRecord
  validate :same_email
  validates :sender, presence: {message: "发送邮箱不能空"}
  validates :receiver, presence: {message: "接收邮箱不能空"}
  validates :subject, presence: {message: "邮件主题不能空"}
  validates :body, presence: {message: "邮件内容不能空"}

  private

  def same_email
    if self.receiver == self.sender
      errors.add(:base, "发送邮箱和接收邮箱不能一样")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/local_emails_controller.rb
class LocalEmailsController < ApplicationController

  before_action :find_mail, except: [:new, :create, :index]

  def index
    @mails = LocalEmail.all
  end

  def show

  end

  def new
    @mail = LocalEmail.new
  end

  def create
    ActiveRecord::Base.transaction do
      begin
        @mail = LocalEmail.new(mail_params)
        if @mail.save
          redirect_to @mail
        else
          render :new
        end
      rescue Exception => e
        Rails.logger.info(e)
      end
    end
  end

  def edit

  end

  def update
    ActiveRecord::Base.transaction do
      begin
        #编辑后，应设置为未发送状态
        if @mail.update_attributes(mail_params.merge(is_send: 0))
          redirect_to @mail
        else
          render :edit
        end
      rescue Exception => e
        Rails.logger.info(e)
      end
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      begin
        if @mail.destroy
          redirect_to root_path
        else
          redirect_to @mail
        end
      rescue Exception => e
        Rails.logger.info(e)
      end
    end
  end

  def send_mail
    ActiveRecord::Base.transaction do
      begin
        LearnMailJob.perform_now(@mail)
        redirect_to @mail
      rescue Exception => e
        Rails.logger.info(e)
      end
    end
  end

  private

  def mail_params
    params.require(:local_email).permit(:subject, :body, :receiver, :sender)
  end

  def find_mail
    @mail = LocalEmail.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/local_emails_helper.rb
module LocalEmailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="container">
    <h3 class="text-center mbt20">
      <%= link_to "邮件发送示例",root_path %>
    </h3>
    <%= yield %>
  </div>
  </body>
</html>

app/views/local_emails/_form.html.erb
<div class="flashMessage" >
  <% @mail.errors.each do |message_type, message| %>
    <div class="pd10"><%= message.html_safe %></div>
  <% end %>
</div>

<%= form_for @mail do |mail| %>
  <div class="pbt10">
    <label for="">发送邮箱: </label>
    <%= mail.text_field :sender,class: "form-control", placeholder: "输入发送邮箱" %>
  </div>
  <div class="pbt10">
    <label for="">接收邮箱: </label>
    <%= mail.text_field :receiver,class: "form-control", placeholder: "输入接收邮箱" %>
  </div>
  <div class="pbt10">
    <label for="">发送主题: </label>
    <%= mail.text_field :subject,class: "form-control", placeholder: "输入发送主题" %>
  </div>
  <div class="pbt10">
    <label for="">邮件内容: </label>
    <%= mail.text_area :body, class: "width100", placeholder: "邮件内容", rows: 7 %>
  </div>
  <div class="mbt10">
    <%= mail.submit "提交", class: "btn btn-primary", 'data-disable-with': "提交中..." %>
    <%= link_to "取消", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/local_emails/edit.html.erb
<div class="mbt20">
  <h4>编辑邮件</h4>
</div>
<div>
  <%= render partial: "local_emails/form" %>
</div>

app/views/local_emails/index.html.erb
<div class="mbt20">
  <%= link_to "创建新的邮件",new_local_email_path, class: "btn btn-primary" %>
</div>
<div class="mbt20">
  <% @mails.find_each do |mail| %>
  <div class="pbt10">
    <%= link_to mail.subject, mail %>
    <span class="plr10">
      <%= link_to "编辑", edit_local_email_path(mail), class: "text-gray" %>
    </span>
    <span>
      <%= link_to "删除", local_email_path(mail), method: :delete, class: "text-gray", data: {confirm: "确认删除吗？"} %>
    </span>
    <span class="plr10">
      <% if mail.is_send == 1 %>
        <%= link_to "已发送", "javascript:void(0)", class: "text-green" %>
      <% elsif mail.is_send == 2 %>
        <%= link_to "发送失败", send_mail_local_email_path(mail), method: :post, class: "text-red" %>
      <% else %>
        <%= link_to "立即发送", send_mail_local_email_path(mail), method: :post, class: "text-blue" %>
      <% end %>
    </span>
  </div>
  <% end %>
</div>

app/views/local_emails/new.html.erb
<div class="mbt20">
  <h4>新建邮件</h4>
</div>
<div>
  <%= render partial: "local_emails/form" %>
</div>

app/views/local_emails/show.html.erb
<div>
  <h4><span class="text-gray">发送主题：</span><%= @mail.subject %></h4>
  <div>
    <span class="text-gray">发送邮箱：</span><span><%= @mail.sender %></span>
  </div>
  <div class="pbt10">
    <span class="text-gray">接收邮箱：</span><span><%= @mail.receiver %></span>
  </div>
</div>
<div class="mbt20">
  <div class="pbt10 text-gray">邮件内容：</div>
  <div><%= @mail.body %></div>
</div>
<div>
  <span class="plr10">
    <%= link_to "编辑", edit_local_email_path(@mail),class: "btn btn-default" %>
  </span>
  <span class="plr10">
    <%= link_to "删除", local_email_path(@mail),method: :delete, class: "btn btn-default", data: {confirm: "确认删除吗？"} %>
  </span>
  <span class="plr10">
    <% if @mail.is_send == 1 %>
        <%= link_to "已发送", "javascript:void(0)", class: "btn btn-default" %>
      <% elsif @mail.is_send == 2 %>
        <%= link_to "发送失败", send_mail_local_email_path(@mail), method: :post, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "立即发送", send_mail_local_email_path(@mail), method: :post, class: "btn btn-primary" %>
      <% end %>
  </span>

</div>